#include "CGAPython.h"

namespace py = pybind11;


//注册python模块
PYBIND11_MODULE(CGAPython, m) {
	m.doc() = "pybind11 CGAPython";
	//m.def("CreateInterface", &CGA::CreateInterface);

	py::class_<CGA::cga_game_data_t>(m, "cga_game_data_t")
		.def(py::init<>())
		.def_readwrite("reserved", &CGA::cga_game_data_t::reserved);
	py::class_<CGA::cga_sys_time_t>(m, "cga_game_data_t")
		.def(py::init<>())
		.def_readwrite("years", &CGA::cga_sys_time_t::years)
		.def_readwrite("month", &CGA::cga_sys_time_t::month)
		.def_readwrite("days", &CGA::cga_sys_time_t::days)
		.def_readwrite("hours", &CGA::cga_sys_time_t::hours)
		.def_readwrite("mins", &CGA::cga_sys_time_t::mins)
		.def_readwrite("secs", &CGA::cga_sys_time_t::secs)
		.def_readwrite("local_time", &CGA::cga_sys_time_t::local_time)
		.def_readwrite("server_time", &CGA::cga_sys_time_t::server_time)
		;
	py::class_<CGA::cga_player_info_t>(m, "cga_game_data_t")
		.def(py::init<>())
		.def_readwrite("hp", &CGA::cga_player_info_t::hp)
		.def_readwrite("maxhp", &CGA::cga_player_info_t::maxhp)
		.def_readwrite("mp", &CGA::cga_player_info_t::mp)
		.def_readwrite("maxmp", &CGA::cga_player_info_t::maxmp)
		.def_readwrite("maxxp", &CGA::cga_player_info_t::maxxp)
		.def_readwrite("health", &CGA::cga_player_info_t::health)
		.def_readwrite("souls", &CGA::cga_player_info_t::souls)
		.def_readwrite("level", &CGA::cga_player_info_t::level)
		.def_readwrite("gold", &CGA::cga_player_info_t::gold)
		.def_readwrite("score", &CGA::cga_player_info_t::score)
		.def_readwrite("skillslots", &CGA::cga_player_info_t::skillslots)
		.def_readwrite("use_title", &CGA::cga_player_info_t::use_title)
		.def_readwrite("avatar_id", &CGA::cga_player_info_t::avatar_id)
		.def_readwrite("image_id", &CGA::cga_player_info_t::image_id)
		.def_readwrite("unitid", &CGA::cga_player_info_t::unitid)
		.def_readwrite("petid", &CGA::cga_player_info_t::petid)
		.def_readwrite("direction", &CGA::cga_player_info_t::direction)
		.def_readwrite("battle_position", &CGA::cga_player_info_t::battle_position)
		.def_readwrite("punchclock", &CGA::cga_player_info_t::punchclock)
		.def_readwrite("manu_endurance", &CGA::cga_player_info_t::manu_endurance)
		.def_readwrite("manu_skillful", &CGA::cga_player_info_t::manu_skillful)
		.def_readwrite("manu_intelligence", &CGA::cga_player_info_t::manu_intelligence)
		.def_readwrite("value_charisma", &CGA::cga_player_info_t::value_charisma)
		.def_readwrite("usingpunchclock", &CGA::cga_player_info_t::usingpunchclock)
		.def_readwrite("petriding", &CGA::cga_player_info_t::usingpunchclock)
		.def_readwrite("name", &CGA::cga_player_info_t::name)
		.def_readwrite("job", &CGA::cga_player_info_t::job)
		.def_readwrite("nick", &CGA::cga_player_info_t::nick)
		.def_readwrite("detail", &CGA::cga_player_info_t::detail)
		.def_readwrite("titles", &CGA::cga_player_info_t::titles)
		.def_readwrite("persdesc", &CGA::cga_player_info_t::persdesc)
		.def_readwrite("gid", &CGA::cga_player_info_t::gid)
		.def_readwrite("player_index", &CGA::cga_player_info_t::player_index)
		;
	py::class_<CGA::cga_chat_msg_t>(m, "cga_chat_msg_t")
		.def(py::init<>())
		.def_readwrite("unitid", &CGA::cga_chat_msg_t::unitid)
		.def_readwrite("msg", &CGA::cga_chat_msg_t::msg)
		.def_readwrite("color", &CGA::cga_chat_msg_t::color)
		.def_readwrite("size", &CGA::cga_chat_msg_t::size);
	py::class_<CGA::cga_player_menu_item_t>(m, "cga_player_menu_item_t")
		.def(py::init<>())
		.def_readwrite("name", &CGA::cga_player_menu_item_t::name)
		.def_readwrite("index", &CGA::cga_player_menu_item_t::index)
		.def_readwrite("color", &CGA::cga_player_menu_item_t::color);
	py::class_<CGA::cga_unit_menu_item_t>(m, "cga_unit_menu_item_t")
		.def(py::init<>())
		.def_readwrite("name", &CGA::cga_unit_menu_item_t::name)
		.def_readwrite("level", &CGA::cga_unit_menu_item_t::level)
		.def_readwrite("health", &CGA::cga_unit_menu_item_t::health)
		.def_readwrite("hp", &CGA::cga_unit_menu_item_t::hp)
		.def_readwrite("maxhp", &CGA::cga_unit_menu_item_t::maxhp)
		.def_readwrite("mp", &CGA::cga_unit_menu_item_t::mp)
		.def_readwrite("maxmp", &CGA::cga_unit_menu_item_t::maxmp)
		.def_readwrite("color", &CGA::cga_unit_menu_item_t::color)
		.def_readwrite("index", &CGA::cga_unit_menu_item_t::index)
		;
	py::class_<CGA::cga_npc_dialog_t>(m, "cga_npc_dialog_t")
		.def(py::init<>())
		.def_readwrite("type", &CGA::cga_npc_dialog_t::type)
		.def_readwrite("options", &CGA::cga_npc_dialog_t::options)
		.def_readwrite("dialog_id", &CGA::cga_npc_dialog_t::dialog_id)
		.def_readwrite("npc_id", &CGA::cga_npc_dialog_t::npc_id)
		.def_readwrite("message", &CGA::cga_npc_dialog_t::message)
		;

	py::class_<CGA::cga_working_result_t>(m, "cga_working_result_t")
		.def(py::init<>())
		.def_readwrite("type", &CGA::cga_working_result_t::type)
		.def_readwrite("success", &CGA::cga_working_result_t::success)
		.def_readwrite("levelup", &CGA::cga_working_result_t::levelup)
		.def_readwrite("xp", &CGA::cga_working_result_t::xp)
		.def_readwrite("count", &CGA::cga_working_result_t::count)
		.def_readwrite("endurance", &CGA::cga_working_result_t::endurance)
		.def_readwrite("skillful", &CGA::cga_working_result_t::skillful)
		.def_readwrite("intelligence", &CGA::cga_working_result_t::intelligence)
		.def_readwrite("name", &CGA::cga_working_result_t::name)
		.def_readwrite("value", &CGA::cga_working_result_t::value)
		.def_readwrite("imgid", &CGA::cga_working_result_t::imgid)
		.def_readwrite("status", &CGA::cga_working_result_t::status)
		.def_readwrite("value2", &CGA::cga_working_result_t::value2)
		.def_readwrite("count", &CGA::cga_working_result_t::count)
		.def_readwrite("unk", &CGA::cga_working_result_t::unk)
		;
	py::class_<CGA::cga_trade_stuff_info_t>(m, "cga_trade_stuff_info_t")
		.def(py::init<>())
		.def_readwrite("items", &CGA::cga_trade_stuff_info_t::items)
		.def_readwrite("pet", &CGA::cga_trade_stuff_info_t::pet)
		.def_readwrite("petskills", &CGA::cga_trade_stuff_info_t::petskills)
		.def_readwrite("gold", &CGA::cga_trade_stuff_info_t::gold)
		.def_readwrite("type", &CGA::cga_trade_stuff_info_t::type)
		;
	py::class_<CGA::cga_item_info_t>(m, "cga_item_info_t")
		.def(py::init<>())
		.def_readwrite("name", &CGA::cga_item_info_t::name)
		.def_readwrite("attr", &CGA::cga_item_info_t::attr)
		.def_readwrite("info", &CGA::cga_item_info_t::info)
		.def_readwrite("itemid", &CGA::cga_item_info_t::itemid)
		.def_readwrite("count", &CGA::cga_item_info_t::count)
		.def_readwrite("pos", &CGA::cga_item_info_t::pos)
		.def_readwrite("level", &CGA::cga_item_info_t::level)
		.def_readwrite("type", &CGA::cga_item_info_t::type)
		.def_readwrite("assessed", &CGA::cga_item_info_t::assessed)
		.def_readwrite("assess_flags", &CGA::cga_item_info_t::assess_flags)
		.def_readwrite("image_id", &CGA::cga_item_info_t::image_id)
		;
	py::class_<CGAPython>(m, "CGA")
		.def(py::init<>())
		.def("IsConnected", &CGAPython::IsConnected)
		.def("Disconnect", &CGAPython::Disconnect)
		.def("Connect", &CGAPython::Connect)
		//.def("Initialize", &CGAPython::Initialize)
		.def("IsInGame", &CGAPython::IsInGame)

		.def("GetWorldStatus", &CGAPython::GetWorldStatus)
		.def("GetGameStatus", &CGAPython::GetGameStatus)
		.def("GetBGMIndex", &CGAPython::GetBGMIndex)
		.def("RegisterChatMsgNotify", &CGAPython::RegisterChatMsgNotify)
		.def("RegisterServerShutdownNotify", &CGAPython::RegisterServerShutdownNotify)
		.def("RegisterGameWndKeyDownNotify", &CGAPython::RegisterGameWndKeyDownNotify)
		.def("RegisterBattleActionNotify", &CGAPython::RegisterBattleActionNotify)
		.def("RegisterPlayerMenuNotify", &CGAPython::RegisterPlayerMenuNotify)
		.def("RegisterNPCDialogNotify", &CGAPython::RegisterNPCDialogNotify)
		.def("RegisterWorkingResultNotify", &CGAPython::RegisterWorkingResultNotify)
		.def("RegisterTradeStuffsNotify", &CGAPython::RegisterTradeStuffsNotify)
		.def("RegisterTradeDialogNotify", &CGAPython::RegisterTradeDialogNotify)
		.def("RegisterTradeStateNotify", &CGAPython::RegisterTradeStateNotify)
		.def("RegisterDownloadMapNotify", &CGAPython::RegisterDownloadMapNotify)
		.def("RegisterConnectionStateNotify", &CGAPython::RegisterConnectionStateNotify)
		;

}